services:
  react-native:
    container_name: myapp-react-native
    tty: true
    build:
      context: ./ReactNative
      dockerfile: ./Dockerfile
    volumes:
      - /ReactNative/node_modules
      - ./ReactNative:/ReactNative
    env_file: ./.env
    ports:
      - "8081:8081"
    command: 
      - expo
      - start
      - --tunnel
